"""empty message

Revision ID: 2b6886bbb5d8
Revises: 30c556b03d74
Create Date: 2014-10-09 21:10:26.387349

"""

# revision identifiers, used by Alembic.
revision = '2b6886bbb5d8'
down_revision = '30c556b03d74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
