"""empty message

Revision ID: 474e139f1b80
Revises: 4b774b362fb
Create Date: 2014-10-07 19:29:20.941558

"""

# revision identifiers, used by Alembic.
revision = '474e139f1b80'
down_revision = '4b774b362fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
