"""empty message

Revision ID: 4b774b362fb
Revises: 20c51fcc4ca0
Create Date: 2014-10-07 19:29:09.766782

"""

# revision identifiers, used by Alembic.
revision = '4b774b362fb'
down_revision = '20c51fcc4ca0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'permissions')
    ### end Alembic commands ###
